"""empty message

Revision ID: fe8cd5fcf902
Revises: 3265f158319e
Create Date: 2023-05-31 09:05:36.345047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8cd5fcf902'
down_revision = '3265f158319e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('attack',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('defense',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sp_atk',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sp_def',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('speed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('generation',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('generation',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('speed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sp_def',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sp_atk',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('defense',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('attack',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('hp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
